/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.  ## Rate limiting  Requests are rate limited per workspace (shared across all API tokens of the workspace). The exact limit depends on your subscription plan.  Every response advertises the current limit state through headers:  - `RateLimit` and `RateLimit-Policy` — IETF rate-limit headers describing the   active policies and how much of each one is left. - `X-RateLimit-Limit` — maximum number of requests allowed in the window. - `X-RateLimit-Remaining` — requests left in the current window. - `X-RateLimit-Reset` — Unix timestamp at which the window resets.  Two policies apply at the same time. `rpm` caps the sustained rate over 60 seconds. `burst` caps a short spike over 10 seconds. A request is served only when both policies allow it.  Example headers on a served request, for a plan with a 600 rpm limit:  ``` RateLimit-Policy: \"rpm\";q=600;w=60, \"burst\";q=100;w=10 RateLimit: \"rpm\";r=412;t=37, \"burst\";r=88;t=2 X-RateLimit-Limit: 100 X-RateLimit-Remaining: 88 X-RateLimit-Reset: 1756742400 ```  In `RateLimit-Policy`, `q` is the quota and `w` is the window in seconds. In `RateLimit`, `r` is the requests left and `t` is the seconds until that policy frees a slot.  The `X-RateLimit-*` headers are a single-number mirror for older clients. They report whichever of the two policies is closer to its limit, so they can show the burst quota while a spike is in progress, as in the example above.  When the limit is exceeded the API responds with `429 Too Many Requests`, a `Retry-After` header (seconds to wait before retrying), and the body:  ``` Retry-After: 12 ```  ```json {   \"status\": false,   \"errorMessage\": \"API rate limit exceeded.\" } ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { SystemFieldListResponse } from '../model';
/**
 * SystemFieldsApi - axios parameter creator
 * @export
 */
export const SystemFieldsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This method allows to retrieve all system fields. 
         * @summary Get all System Fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSystemFields: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/system_field`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Token", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SystemFieldsApi - functional programming interface
 * @export
 */
export const SystemFieldsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SystemFieldsApiAxiosParamCreator(configuration)
    return {
        /**
         * This method allows to retrieve all system fields. 
         * @summary Get all System Fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSystemFields(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SystemFieldListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSystemFields(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SystemFieldsApi - factory interface
 * @export
 */
export const SystemFieldsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SystemFieldsApiFp(configuration)
    return {
        /**
         * This method allows to retrieve all system fields. 
         * @summary Get all System Fields
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSystemFields(options?: any): AxiosPromise<SystemFieldListResponse> {
            return localVarFp.getSystemFields(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SystemFieldsApi - object-oriented interface
 * @export
 * @class SystemFieldsApi
 * @extends {BaseAPI}
 */
export class SystemFieldsApi extends BaseAPI {
    /**
     * This method allows to retrieve all system fields. 
     * @summary Get all System Fields
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SystemFieldsApi
     */
    public getSystemFields(options?: AxiosRequestConfig) {
        return SystemFieldsApiFp(this.configuration).getSystemFields(options).then((request) => request(this.axios, this.basePath));
    }
}
