/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v2
 * Qase TestOps API v2 Specification.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RelationSuiteItem } from './relation-suite-item';

/**
 * 
 * @export
 * @interface RelationSuite
 */
export interface RelationSuite {
    /**
     * 
     * @type {Array<RelationSuiteItem>}
     * @memberof RelationSuite
     */
    'data': Array<RelationSuiteItem>;
}

