/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AttachmentUploadsResponseAllOf } from './attachment-uploads-response-all-of';
import { Attachmentupload } from './attachmentupload';
import { BaseResponse } from './base-response';

/**
 * @type AttachmentUploadsResponse
 * @export
 */
export type AttachmentUploadsResponse = AttachmentUploadsResponseAllOf & BaseResponse;


