/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface Author
 */
export interface Author {
    /**
     * 
     * @type {number}
     * @memberof Author
     */
    'id'?: number;
    /**
     * Author UUID. Use it to reference the author in other API methods.
     * @type {string}
     * @memberof Author
     */
    'uuid'?: string;
    /**
     * Deprecated, use `uuid` instead.
     * @type {number}
     * @memberof Author
     * @deprecated
     */
    'author_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Author
     */
    'entity_type'?: string;
    /**
     * 
     * @type {number}
     * @memberof Author
     */
    'entity_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Author
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof Author
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Author
     */
    'is_active'?: boolean;
}

