/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Bulk200ResponseAllOfResult } from './bulk200-response-all-of-result';

/**
 * 
 * @export
 * @interface Bulk200ResponseAllOf
 */
export interface Bulk200ResponseAllOf {
    /**
     * 
     * @type {Bulk200ResponseAllOfResult}
     * @memberof Bulk200ResponseAllOf
     */
    'result'?: Bulk200ResponseAllOfResult;
}

