/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ConfigurationItem } from './configuration-item';

/**
 * 
 * @export
 * @interface ConfigurationGroup
 */
export interface ConfigurationGroup {
    /**
     * 
     * @type {number}
     * @memberof ConfigurationGroup
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationGroup
     */
    'title'?: string;
    /**
     * 
     * @type {Array<Configuration>}
     * @memberof ConfigurationGroup
     */
    'configurations'?: Array<ConfigurationItem>;
}

