/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.  ## Rate limiting  Requests are rate limited per workspace (shared across all API tokens of the workspace). The exact limit depends on your subscription plan.  Every response advertises the current limit state through headers:  - `RateLimit` and `RateLimit-Policy` — IETF rate-limit headers describing the   active policies and how much of each one is left. - `X-RateLimit-Limit` — maximum number of requests allowed in the window. - `X-RateLimit-Remaining` — requests left in the current window. - `X-RateLimit-Reset` — Unix timestamp at which the window resets.  Two policies apply at the same time. `rpm` caps the sustained rate over 60 seconds. `burst` caps a short spike over 10 seconds. A request is served only when both policies allow it.  Example headers on a served request, for a plan with a 600 rpm limit:  ``` RateLimit-Policy: \"rpm\";q=600;w=60, \"burst\";q=100;w=10 RateLimit: \"rpm\";r=412;t=37, \"burst\";r=88;t=2 X-RateLimit-Limit: 100 X-RateLimit-Remaining: 88 X-RateLimit-Reset: 1756742400 ```  In `RateLimit-Policy`, `q` is the quota and `w` is the window in seconds. In `RateLimit`, `r` is the requests left and `t` is the seconds until that policy frees a slot.  The `X-RateLimit-*` headers are a single-number mirror for older clients. They report whichever of the two policies is closer to its limit, so they can show the burst quota while a spike is in progress, as in the example above.  When the limit is exceeded the API responds with `429 Too Many Requests`, a `Retry-After` header (seconds to wait before retrying), and the body:  ``` Retry-After: 12 ```  ```json {   \"status\": false,   \"errorMessage\": \"API rate limit exceeded.\" } ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface DefectUpdate
 */
export interface DefectUpdate {
    /**
     * 
     * @type {string}
     * @memberof DefectUpdate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof DefectUpdate
     */
    'actual_result'?: string;
    /**
     * 
     * @type {number}
     * @memberof DefectUpdate
     */
    'severity'?: number;
    /**
     * 
     * @type {number}
     * @memberof DefectUpdate
     */
    'milestone_id'?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DefectUpdate
     */
    'attachments'?: Array<string>;
    /**
     * Custom field values keyed by the field\'s project-scoped `internal_id` (see `GET /custom_field`). Values are always **scalar strings**; arrays, objects or non-scalars are rejected.  | Field type           | Value format                              | Example                 | |----------------------|-------------------------------------------|-------------------------| | `string`, `text`     | Plain string                              | `\"hello\"`               | | `number`             | Numeric string                            | `\"42\"`                  | | `url`                | Valid URL                                 | `\"https://qase.io\"`     | | `datetime`           | Absolute date (ISO 8601 recommended)      | `\"2026-04-29T15:00:00Z\"`| | `selectbox`, `radio` | Option `id` as string                     | `\"1\"`                   | | `multiselect`        | Comma-separated option `id`s (no spaces)  | `\"1,2,3\"`               | | `checkbox`           | `\"1\"` to check, `\"\"` to uncheck           | `\"1\"`                   | | `user`               | Team member `internal_id` as string       | `\"42\"`                  |  Partial update: only fields present in the payload are validated; required fields not included are not enforced. Send `\"\"` to clear a value. Unknown `internal_id`s are rejected; option-based values must reference an existing option.  Note: a `required` checkbox without a default cannot be unchecked via the API — set a default or clear `required` in workspace settings. 
     * @type {{ [key: string]: string; }}
     * @memberof DefectUpdate
     */
    'custom_field'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof DefectUpdate
     */
    'tags'?: Array<string>;
}

