/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DefectUpdate
 */
export interface DefectUpdate {
    /**
     * 
     * @type {string}
     * @memberof DefectUpdate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof DefectUpdate
     */
    'actual_result'?: string;
    /**
     * 
     * @type {number}
     * @memberof DefectUpdate
     */
    'severity'?: number;
    /**
     * 
     * @type {number}
     * @memberof DefectUpdate
     */
    'milestone_id'?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof DefectUpdate
     */
    'attachments'?: Array<string>;
    /**
     * A map of custom fields values (id => value)
     * @type {{ [key: string]: string; }}
     * @memberof DefectUpdate
     */
    'custom_field'?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof DefectUpdate
     */
    'tags'?: Array<string>;
}

