/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface Environment
 */
export interface Environment {
    /**
     * 
     * @type {number}
     * @memberof Environment
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Environment
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Environment
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Environment
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof Environment
     */
    'host'?: string | null;
}

