/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProjectCountsDefects } from './project-counts-defects';
import { ProjectCountsRuns } from './project-counts-runs';

/**
 * 
 * @export
 * @interface ProjectCounts
 */
export interface ProjectCounts {
    /**
     * 
     * @type {number}
     * @memberof ProjectCounts
     */
    'cases'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectCounts
     */
    'suites'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProjectCounts
     */
    'milestones'?: number;
    /**
     * 
     * @type {ProjectCountsRuns}
     * @memberof ProjectCounts
     */
    'runs'?: ProjectCountsRuns;
    /**
     * 
     * @type {ProjectCountsDefects}
     * @memberof ProjectCounts
     */
    'defects'?: ProjectCountsDefects;
}

