/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ProjectCreate
 */
export interface ProjectCreate {
    /**
     * Project title.
     * @type {string}
     * @memberof ProjectCreate
     */
    'title': string;
    /**
     * Project code. Unique for team. Digits and special characters are not allowed.
     * @type {string}
     * @memberof ProjectCreate
     */
    'code': string;
    /**
     * Project description.
     * @type {string}
     * @memberof ProjectCreate
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreate
     */
    'access'?: ProjectCreateAccessEnum;
    /**
     * Team group hash. Required if access param is set to group.
     * @type {string}
     * @memberof ProjectCreate
     */
    'group'?: string;
    /**
     * Additional project settings.
     * @type {{ [key: string]: any; }}
     * @memberof ProjectCreate
     */
    'settings'?: { [key: string]: any; };
}

/**
    * @export
    * @enum {string}
    */
export enum ProjectCreateAccessEnum {
    ALL = 'all',
    GROUP = 'group',
    NONE = 'none'
}


