/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface QqlPlan
 */
export interface QqlPlan {
    /**
     * 
     * @type {number}
     * @memberof QqlPlan
     */
    'plan_id': number;
    /**
     * 
     * @type {number}
     * @memberof QqlPlan
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof QqlPlan
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof QqlPlan
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof QqlPlan
     */
    'cases_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof QqlPlan
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof QqlPlan
     */
    'updated_at'?: string;
}

