/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReviewReviewersInner } from './review-reviewers-inner';

/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * Review ID, unique within the project.
     * @type {number}
     * @memberof Review
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    'title'?: string;
    /**
     * `create` — the review proposes a new test case; `edit` — the review proposes changes to an existing test case.
     * @type {string}
     * @memberof Review
     */
    'type'?: ReviewTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    'status'?: ReviewStatusEnum;
    /**
     * ID of the reviewed test case. Null for new-case draft reviews.
     * @type {number}
     * @memberof Review
     */
    'case_id'?: number | null;
    /**
     * Author UUID of the review creator (see `GET /author`).
     * @type {string}
     * @memberof Review
     */
    'author_uuid'?: string | null;
    /**
     * 
     * @type {Array<ReviewReviewersInner>}
     * @memberof Review
     */
    'reviewers'?: Array<ReviewReviewersInner>;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    'updated_at'?: string | null;
}

/**
    * @export
    * @enum {string}
    */
export enum ReviewTypeEnum {
    CREATE = 'create',
    EDIT = 'edit'
}
/**
    * @export
    * @enum {string}
    */
export enum ReviewStatusEnum {
    OPEN = 'open',
    MERGED = 'merged',
    DECLINED = 'declined'
}


