/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReviewCaseData } from './review-case-data';

/**
 * 
 * @export
 * @interface ReviewUpdate
 */
export interface ReviewUpdate {
    /**
     * Author UUIDs of team members assigned as reviewers (see `GET /author`). When provided, replaces the current reviewer list; an empty array removes all reviewers. Omit to leave reviewers unchanged.
     * @type {Array<string>}
     * @memberof ReviewUpdate
     */
    'reviewers'?: Array<string>;
    /**
     * Sent fields are merged into the stored proposal. Changing the proposal resets all existing approvals; updating only the reviewers keeps them.
     * @type {ReviewCaseData}
     * @memberof ReviewUpdate
     */
    'proposed_case'?: ReviewCaseData;
}

