/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ReviewProposedStep
 */
export interface ReviewProposedStep {
    /**
     * Step action text. Used for classic steps. For gherkin steps, use the \"value\" property instead.
     * @type {string}
     * @memberof ReviewProposedStep
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewProposedStep
     */
    'expected_result'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewProposedStep
     */
    'data'?: string;
    /**
     * Gherkin scenario text. Used when steps_type is \"gherkin\".
     * @type {string}
     * @memberof ReviewProposedStep
     */
    'value'?: string;
    /**
     * Hash of the referenced shared step.
     * @type {string}
     * @memberof ReviewProposedStep
     */
    'shared'?: string;
    /**
     * A list of Attachment hashes.
     * @type {Array<string>}
     * @memberof ReviewProposedStep
     */
    'attachments'?: Array<string>;
    /**
     * Nested steps use the same structure.
     * @type {Array<object>}
     * @memberof ReviewProposedStep
     */
    'steps'?: Array<object>;
}

