/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReviewCaseData } from './review-case-data';

/**
 * 
 * @export
 * @interface ReviewCreate
 */
export interface ReviewCreate {
    /**
     * For `create` reviews `title` and all required project fields are required. For `edit` reviews send only the fields the proposal changes.
     * @type {ReviewCaseData}
     * @memberof ReviewCreate
     */
    'proposed_case': ReviewCaseData;
    /**
     * ID of the reviewed test case. When present an `edit` review is created, otherwise a `create` review with a new-case draft.
     * @type {number}
     * @memberof ReviewCreate
     */
    'case_id'?: number | null;
    /**
     * Author UUIDs of team members to assign as reviewers (see `GET /author`).
     * @type {Array<string>}
     * @memberof ReviewCreate
     */
    'reviewers'?: Array<string>;
}

