/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReviewCreate } from './review-create';

/**
 * 
 * @export
 * @interface ReviewBulk
 */
export interface ReviewBulk {
    /**
     * Validated as a whole: if any item is invalid nothing is created. Otherwise each item is processed on its own and reported in the response.
     * @type {Array<ReviewCreate>}
     * @memberof ReviewBulk
     */
    'reviews': Array<ReviewCreate>;
}

