/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface ReviewReviewersInner
 */
export interface ReviewReviewersInner {
    /**
     * Author UUID of the reviewer (see `GET /author`).
     * @type {string}
     * @memberof ReviewReviewersInner
     */
    'author_uuid'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReviewReviewersInner
     */
    'status'?: ReviewReviewersInnerStatusEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum ReviewReviewersInnerStatusEnum {
    UNAPPROVED = 'unapproved',
    APPROVED = 'approved',
    CHANGES_REQUESTED = 'changes_requested'
}


