/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RunExternalIssuesLinksInner } from './run-external-issues-links-inner';

/**
 * 
 * @export
 * @interface RunExternalIssues
 */
export interface RunExternalIssues {
    /**
     * 
     * @type {string}
     * @memberof RunExternalIssues
     */
    'type': RunExternalIssuesTypeEnum;
    /**
     * Array of external issue links. Each test run (run_id) can have only one external issue link.
     * @type {Array<RunExternalIssuesLinksInner>}
     * @memberof RunExternalIssues
     */
    'links': Array<RunExternalIssuesLinksInner>;
}

/**
    * @export
    * @enum {string}
    */
export enum RunExternalIssuesTypeEnum {
    JIRA_CLOUD = 'jira-cloud',
    JIRA_SERVER = 'jira-server'
}


