/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface Runupdate
 */
export interface Runupdate {
    /**
     * 
     * @type {string}
     * @memberof Runupdate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Runupdate
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Runupdate
     */
    'environment_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Runupdate
     */
    'environment_slug'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Runupdate
     */
    'milestone_id'?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Runupdate
     */
    'tags'?: Array<string> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof Runupdate
     */
    'configurations'?: Array<number> | null;
    /**
     * Custom field values keyed by the field\'s project-scoped `internal_id` (see `GET /custom_field`). Values are always **scalar strings**; arrays, objects or non-scalars are rejected.  | Field type           | Value format                              | Example                 | |----------------------|-------------------------------------------|-------------------------| | `string`, `text`     | Plain string                              | `\"hello\"`               | | `number`             | Numeric string                            | `\"42\"`                  | | `url`                | Valid URL                                 | `\"https://qase.io\"`     | | `datetime`           | Absolute date (ISO 8601 recommended)      | `\"2026-04-29T15:00:00Z\"`| | `selectbox`, `radio` | Option `id` as string                     | `\"1\"`                   | | `multiselect`        | Comma-separated option `id`s (no spaces)  | `\"1,2,3\"`               | | `checkbox`           | `\"1\"` to check, `\"\"` to uncheck           | `\"1\"`                   | | `user`               | Team member `internal_id` as string       | `\"42\"`                  |  Validation: all required fields without a default value must be present and non-empty; unknown `internal_id`s are rejected; option-based values must reference an existing option.  Note: a `required` checkbox without a default cannot be unchecked via the API — set a default or clear `required` in workspace settings. 
     * @type {{ [key: string]: string; }}
     * @memberof Runupdate
     */
    'custom_field'?: { [key: string]: string; } | null;
}

