/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Runupdate
 */
export interface Runupdate {
    /**
     * 
     * @type {string}
     * @memberof Runupdate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Runupdate
     */
    'description'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Runupdate
     */
    'environment_id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Runupdate
     */
    'environment_slug'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Runupdate
     */
    'milestone_id'?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof Runupdate
     */
    'tags'?: Array<string> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof Runupdate
     */
    'configurations'?: Array<number> | null;
    /**
     * A map of custom fields values (id => value)
     * @type {{ [key: string]: string; }}
     * @memberof Runupdate
     */
    'custom_field'?: { [key: string]: string; } | null;
}

