/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseResponse } from './base-response';
import { SharedParameterListResponseAllOf } from './shared-parameter-list-response-all-of';
import { SharedParameterListResponseAllOfResult } from './shared-parameter-list-response-all-of-result';

/**
 * @type SharedParameterListResponse
 * @export
 */
export type SharedParameterListResponse = BaseResponse & SharedParameterListResponseAllOf;


