/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface Suite
 */
export interface Suite {
    /**
     * 
     * @type {number}
     * @memberof Suite
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Suite
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Suite
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Suite
     */
    'preconditions'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Suite
     */
    'position'?: number;
    /**
     * 
     * @type {number}
     * @memberof Suite
     */
    'cases_count'?: number;
    /**
     * 
     * @type {number}
     * @memberof Suite
     */
    'parent_id'?: number | null;
    /**
     * Deprecated, use the `created_at` property instead.
     * @type {string}
     * @memberof Suite
     * @deprecated
     */
    'created'?: string;
    /**
     * Deprecated, use the `updated_at` property instead.
     * @type {string}
     * @memberof Suite
     * @deprecated
     */
    'updated'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Suite
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Suite
     */
    'updated_at'?: string;
}

