/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BaseResponse } from './base-response';
import { SuiteListResponseAllOf } from './suite-list-response-all-of';
import { SuiteListResponseAllOfResult } from './suite-list-response-all-of-result';

/**
 * @type SuiteListResponse
 * @export
 */
export type SuiteListResponse = BaseResponse & SuiteListResponseAllOf;


