/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ParameterSingle } from './parameter-single';

/**
 * Single parameter
 * @export
 * @interface TestCaseParameterSingleAllOf
 */
export interface TestCaseParameterSingleAllOf {
    /**
     * 
     * @type {ParameterSingle}
     * @memberof TestCaseParameterSingleAllOf
     */
    'item': ParameterSingle;
    /**
     * 
     * @type {string}
     * @memberof TestCaseParameterSingleAllOf
     */
    'type'?: TestCaseParameterSingleAllOfTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum TestCaseParameterSingleAllOfTypeEnum {
    SINGLE = 'single'
}


