/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TestStepCreate
 */
export interface TestStepCreate {
    /**
     * 
     * @type {string}
     * @memberof TestStepCreate
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestStepCreate
     */
    'expected_result'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestStepCreate
     */
    'data'?: string;
    /**
     * 
     * @type {number}
     * @memberof TestStepCreate
     * @deprecated
     */
    'position'?: number;
    /**
     * A list of Attachment hashes.
     * @type {Array<string>}
     * @memberof TestStepCreate
     */
    'attachments'?: Array<string>;
    /**
     * Nested steps may be passed here. Use same structure for them.
     * @type {Array<object>}
     * @memberof TestStepCreate
     */
    'steps'?: Array<object>;
}

