/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io TestOps API v1
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TestCaseParameterCreate } from './test-case-parameter-create';
import { TestStepCreate } from './test-step-create';

/**
 * 
 * @export
 * @interface TestCaseCreate
 */
export interface TestCaseCreate {
    /**
     * 
     * @type {string}
     * @memberof TestCaseCreate
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof TestCaseCreate
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCaseCreate
     */
    'preconditions'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCaseCreate
     */
    'postconditions'?: string;
    /**
     * 
     * @type {number}
     * @memberof TestCaseCreate
     */
    'severity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TestCaseCreate
     */
    'priority'?: number;
    /**
     * 
     * @type {number}
     * @memberof TestCaseCreate
     */
    'behavior'?: number;
    /**
     * 
     * @type {number}
     * @memberof TestCaseCreate
     */
    'type'?: number;
    /**
     * 
     * @type {number}
     * @memberof TestCaseCreate
     */
    'layer'?: number;
    /**
     * 
     * @type {number}
     * @memberof TestCaseCreate
     */
    'is_flaky'?: number;
    /**
     * 
     * @type {number}
     * @memberof TestCaseCreate
     */
    'suite_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof TestCaseCreate
     */
    'milestone_id'?: number;
    /**
     * Deprecated, use `isManual` and `isToBeAutomated` instead. Encodes the test case automation state as a single integer: `0` = manual, `1` = manual planned to be automated, `2` = automated. If both `automation` and `isManual`/`isToBeAutomated` are provided, `isManual` and `isToBeAutomated` take precedence.
     * @type {number}
     * @memberof TestCaseCreate
     * @deprecated
     */
    'automation'?: number;
    /**
     * `1` if the case is manual, `0` if it is automated. Combined with `isToBeAutomated`, replaces the deprecated `automation` field.
     * @type {number}
     * @memberof TestCaseCreate
     */
    'isManual'?: number;
    /**
     * `1` if a manual case is planned to be automated, `0` otherwise. Only meaningful when `isManual = 1`; ignored when `isManual = 0`.
     * @type {number}
     * @memberof TestCaseCreate
     */
    'isToBeAutomated'?: number;
    /**
     * 
     * @type {number}
     * @memberof TestCaseCreate
     */
    'status'?: number;
    /**
     * Determines the format of the steps field. When \"classic\", steps use the standard action/expected_result/data format. When \"gherkin\", steps use the {value: \"Given...\\nWhen...\\nThen...\"} format.
     * @type {string}
     * @memberof TestCaseCreate
     */
    'steps_type'?: TestCaseCreateStepsTypeEnum;
    /**
     * A list of Attachment hashes.
     * @type {Array<string>}
     * @memberof TestCaseCreate
     */
    'attachments'?: Array<string>;
    /**
     * 
     * @type {Array<TestStepCreate>}
     * @memberof TestCaseCreate
     */
    'steps'?: Array<TestStepCreate>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TestCaseCreate
     */
    'tags'?: Array<string>;
    /**
     * Deprecated, use `parameters` instead.
     * @type {{ [key: string]: Array<string>; }}
     * @memberof TestCaseCreate
     * @deprecated
     */
    'params'?: { [key: string]: Array<string>; } | null;
    /**
     * 
     * @type {Array<TestCaseParameterCreate>}
     * @memberof TestCaseCreate
     */
    'parameters'?: Array<TestCaseParameterCreate> | null;
    /**
     * Custom field values keyed by the field\'s project-scoped `internal_id` (see `GET /custom_field`). Values are always **scalar strings**; arrays, objects or non-scalars are rejected.  | Field type           | Value format                              | Example                 | |----------------------|-------------------------------------------|-------------------------| | `string`, `text`     | Plain string                              | `\"hello\"`               | | `number`             | Numeric string                            | `\"42\"`                  | | `url`                | Valid URL                                 | `\"https://qase.io\"`     | | `datetime`           | Absolute date (ISO 8601 recommended)      | `\"2026-04-29T15:00:00Z\"`| | `selectbox`, `radio` | Option `id` as string                     | `\"1\"`                   | | `multiselect`        | Comma-separated option `id`s (no spaces)  | `\"1,2,3\"`               | | `checkbox`           | `\"1\"` to check, `\"\"` to uncheck           | `\"1\"`                   | | `user`               | Team member `internal_id` as string       | `\"42\"`                  |  Validation: all required fields without a default value must be present and non-empty; unknown `internal_id`s are rejected; option-based values must reference an existing option.  Note: a `required` checkbox without a default cannot be unchecked via the API — set a default or clear `required` in workspace settings. 
     * @type {{ [key: string]: string; }}
     * @memberof TestCaseCreate
     */
    'custom_field'?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof TestCaseCreate
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCaseCreate
     */
    'updated_at'?: string;
}

/**
    * @export
    * @enum {string}
    */
export enum TestCaseCreateStepsTypeEnum {
    CLASSIC = 'classic',
    GHERKIN = 'gherkin'
}


