/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { GetCasesFiltersParameter } from '../model';
// @ts-ignore
import { IdResponse } from '../model';
// @ts-ignore
import { TestCaseCreate } from '../model';
// @ts-ignore
import { TestCaseListResponse } from '../model';
// @ts-ignore
import { TestCaseResponse } from '../model';
// @ts-ignore
import { TestCaseUpdate } from '../model';
/**
 * CasesApi - axios parameter creator
 * @export
 */
export const CasesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This method allows to create a new test case in selected project. 
         * @summary Create a new test case.
         * @param {string} code Code of project, where to search entities.
         * @param {TestCaseCreate} testCaseCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCase: async (code: string, testCaseCreate: TestCaseCreate, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('createCase', 'code', code)
            // verify required parameter 'testCaseCreate' is not null or undefined
            assertParamExists('createCase', 'testCaseCreate', testCaseCreate)
            const localVarPath = `/case/{code}`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(testCaseCreate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This method completely deletes a test case from repository. 
         * @summary Delete test case.
         * @param {string} code Code of project, where to search entities.
         * @param {number} id Identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCase: async (code: string, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('deleteCase', 'code', code)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteCase', 'id', id)
            const localVarPath = `/case/{code}/{id}`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Token", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This method allows to retrieve a specific test case. 
         * @summary Get a specific test case.
         * @param {string} code Code of project, where to search entities.
         * @param {number} id Identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCase: async (code: string, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('getCase', 'code', code)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCase', 'id', id)
            const localVarPath = `/case/{code}/{id}`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Token", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This method allows to retrieve all test cases stored in selected project. 
         * @summary Get all test cases.
         * @param {string} code Code of project, where to search entities.
         * @param {GetCasesFiltersParameter} [filters] 
         * @param {number} [limit] A number of entities in result set.
         * @param {number} [offset] How many entities should be skipped.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCases: async (code: string, filters?: GetCasesFiltersParameter, limit?: number, offset?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('getCases', 'code', code)
            const localVarPath = `/case/{code}`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Token", configuration)

            if (filters !== undefined) {
                localVarQueryParameter['filters'] = filters;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This method updates a test case. 
         * @summary Update test case.
         * @param {string} code Code of project, where to search entities.
         * @param {number} id Identifier.
         * @param {TestCaseUpdate} testCaseUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCase: async (code: string, id: number, testCaseUpdate: TestCaseUpdate, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'code' is not null or undefined
            assertParamExists('updateCase', 'code', code)
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateCase', 'id', id)
            // verify required parameter 'testCaseUpdate' is not null or undefined
            assertParamExists('updateCase', 'testCaseUpdate', testCaseUpdate)
            const localVarPath = `/case/{code}/{id}`
                .replace(`{${"code"}}`, encodeURIComponent(String(code)))
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication TokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Token", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(testCaseUpdate, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CasesApi - functional programming interface
 * @export
 */
export const CasesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CasesApiAxiosParamCreator(configuration)
    return {
        /**
         * This method allows to create a new test case in selected project. 
         * @summary Create a new test case.
         * @param {string} code Code of project, where to search entities.
         * @param {TestCaseCreate} testCaseCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCase(code: string, testCaseCreate: TestCaseCreate, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IdResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCase(code, testCaseCreate, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This method completely deletes a test case from repository. 
         * @summary Delete test case.
         * @param {string} code Code of project, where to search entities.
         * @param {number} id Identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCase(code: string, id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IdResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCase(code, id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This method allows to retrieve a specific test case. 
         * @summary Get a specific test case.
         * @param {string} code Code of project, where to search entities.
         * @param {number} id Identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCase(code: string, id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TestCaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCase(code, id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This method allows to retrieve all test cases stored in selected project. 
         * @summary Get all test cases.
         * @param {string} code Code of project, where to search entities.
         * @param {GetCasesFiltersParameter} [filters] 
         * @param {number} [limit] A number of entities in result set.
         * @param {number} [offset] How many entities should be skipped.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCases(code: string, filters?: GetCasesFiltersParameter, limit?: number, offset?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TestCaseListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCases(code, filters, limit, offset, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This method updates a test case. 
         * @summary Update test case.
         * @param {string} code Code of project, where to search entities.
         * @param {number} id Identifier.
         * @param {TestCaseUpdate} testCaseUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateCase(code: string, id: number, testCaseUpdate: TestCaseUpdate, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IdResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCase(code, id, testCaseUpdate, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * CasesApi - factory interface
 * @export
 */
export const CasesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CasesApiFp(configuration)
    return {
        /**
         * This method allows to create a new test case in selected project. 
         * @summary Create a new test case.
         * @param {string} code Code of project, where to search entities.
         * @param {TestCaseCreate} testCaseCreate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCase(code: string, testCaseCreate: TestCaseCreate, options?: any): AxiosPromise<IdResponse> {
            return localVarFp.createCase(code, testCaseCreate, options).then((request) => request(axios, basePath));
        },
        /**
         * This method completely deletes a test case from repository. 
         * @summary Delete test case.
         * @param {string} code Code of project, where to search entities.
         * @param {number} id Identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCase(code: string, id: number, options?: any): AxiosPromise<IdResponse> {
            return localVarFp.deleteCase(code, id, options).then((request) => request(axios, basePath));
        },
        /**
         * This method allows to retrieve a specific test case. 
         * @summary Get a specific test case.
         * @param {string} code Code of project, where to search entities.
         * @param {number} id Identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCase(code: string, id: number, options?: any): AxiosPromise<TestCaseResponse> {
            return localVarFp.getCase(code, id, options).then((request) => request(axios, basePath));
        },
        /**
         * This method allows to retrieve all test cases stored in selected project. 
         * @summary Get all test cases.
         * @param {string} code Code of project, where to search entities.
         * @param {GetCasesFiltersParameter} [filters] 
         * @param {number} [limit] A number of entities in result set.
         * @param {number} [offset] How many entities should be skipped.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCases(code: string, filters?: GetCasesFiltersParameter, limit?: number, offset?: number, options?: any): AxiosPromise<TestCaseListResponse> {
            return localVarFp.getCases(code, filters, limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * This method updates a test case. 
         * @summary Update test case.
         * @param {string} code Code of project, where to search entities.
         * @param {number} id Identifier.
         * @param {TestCaseUpdate} testCaseUpdate 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCase(code: string, id: number, testCaseUpdate: TestCaseUpdate, options?: any): AxiosPromise<IdResponse> {
            return localVarFp.updateCase(code, id, testCaseUpdate, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CasesApi - object-oriented interface
 * @export
 * @class CasesApi
 * @extends {BaseAPI}
 */
export class CasesApi extends BaseAPI {
    /**
     * This method allows to create a new test case in selected project. 
     * @summary Create a new test case.
     * @param {string} code Code of project, where to search entities.
     * @param {TestCaseCreate} testCaseCreate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CasesApi
     */
    public createCase(code: string, testCaseCreate: TestCaseCreate, options?: AxiosRequestConfig) {
        return CasesApiFp(this.configuration).createCase(code, testCaseCreate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This method completely deletes a test case from repository. 
     * @summary Delete test case.
     * @param {string} code Code of project, where to search entities.
     * @param {number} id Identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CasesApi
     */
    public deleteCase(code: string, id: number, options?: AxiosRequestConfig) {
        return CasesApiFp(this.configuration).deleteCase(code, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This method allows to retrieve a specific test case. 
     * @summary Get a specific test case.
     * @param {string} code Code of project, where to search entities.
     * @param {number} id Identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CasesApi
     */
    public getCase(code: string, id: number, options?: AxiosRequestConfig) {
        return CasesApiFp(this.configuration).getCase(code, id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This method allows to retrieve all test cases stored in selected project. 
     * @summary Get all test cases.
     * @param {string} code Code of project, where to search entities.
     * @param {GetCasesFiltersParameter} [filters] 
     * @param {number} [limit] A number of entities in result set.
     * @param {number} [offset] How many entities should be skipped.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CasesApi
     */
    public getCases(code: string, filters?: GetCasesFiltersParameter, limit?: number, offset?: number, options?: AxiosRequestConfig) {
        return CasesApiFp(this.configuration).getCases(code, filters, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This method updates a test case. 
     * @summary Update test case.
     * @param {string} code Code of project, where to search entities.
     * @param {number} id Identifier.
     * @param {TestCaseUpdate} testCaseUpdate 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CasesApi
     */
    public updateCase(code: string, id: number, testCaseUpdate: TestCaseUpdate, options?: AxiosRequestConfig) {
        return CasesApiFp(this.configuration).updateCase(code, id, testCaseUpdate, options).then((request) => request(this.axios, this.basePath));
    }
}
