/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AttachmentGet
 */
export interface AttachmentGet {
    /**
     * 
     * @type {string}
     * @memberof AttachmentGet
     */
    'hash'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentGet
     */
    'file'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentGet
     */
    'mime'?: string;
    /**
     * 
     * @type {number}
     * @memberof AttachmentGet
     */
    'size'?: number;
    /**
     * 
     * @type {string}
     * @memberof AttachmentGet
     */
    'extension'?: string;
    /**
     * 
     * @type {string}
     * @memberof AttachmentGet
     */
    'full_path'?: string;
}

