/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Environment } from './environment';
import { EnvironmentResponseAllOf } from './environment-response-all-of';
import { Response } from './response';

/**
 * @type EnvironmentResponse
 * @export
 */
export type EnvironmentResponse = EnvironmentResponseAllOf & Response;


