/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Filters1
 */
export interface Filters1 {
    /**
     * 
     * @type {string}
     * @memberof Filters1
     */
    'entity'?: Filters1EntityEnum;
    /**
     * 
     * @type {string}
     * @memberof Filters1
     */
    'type'?: Filters1TypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum Filters1EntityEnum {
    CASE = 'case',
    RUN = 'run',
    DEFECT = 'defect'
}
/**
    * @export
    * @enum {string}
    */
export enum Filters1TypeEnum {
    STRING = 'string',
    TEXT = 'text',
    NUMBER = 'number',
    CHECKBOX = 'checkbox',
    SELECTBOX = 'selectbox',
    RADIO = 'radio',
    MULTISELECT = 'multiselect',
    URL = 'url',
    USER = 'user',
    DATETIME = 'datetime'
}


