/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetRunsFiltersParameter
 */
export interface GetRunsFiltersParameter {
    /**
     * 
     * @type {string}
     * @memberof GetRunsFiltersParameter
     */
    'search'?: string;
    /**
     * A list of status values separated by comma. Possible values: active, complete, abort. 
     * @type {string}
     * @memberof GetRunsFiltersParameter
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetRunsFiltersParameter
     */
    'milestone'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetRunsFiltersParameter
     */
    'environment'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetRunsFiltersParameter
     */
    'from_start_time'?: number;
    /**
     * 
     * @type {number}
     * @memberof GetRunsFiltersParameter
     */
    'to_start_time'?: number;
}

