/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetCasesFiltersParameter
 */
export interface GetCasesFiltersParameter {
    /**
     * Provide a string that will be used to search by name.
     * @type {string}
     * @memberof GetCasesFiltersParameter
     */
    'search'?: string;
    /**
     * ID of milestone.
     * @type {number}
     * @memberof GetCasesFiltersParameter
     */
    'milestone_id'?: number;
    /**
     * ID of test suite.
     * @type {number}
     * @memberof GetCasesFiltersParameter
     */
    'suite_id'?: number;
    /**
     * A list of severity values separated by comma. Possible values: undefined, blocker, critical, major, normal, minor, trivial 
     * @type {string}
     * @memberof GetCasesFiltersParameter
     */
    'severity'?: string;
    /**
     * A list of priority values separated by comma. Possible values: undefined, high, medium, low 
     * @type {string}
     * @memberof GetCasesFiltersParameter
     */
    'priority'?: string;
    /**
     * A list of type values separated by comma. Possible values: other, functional smoke, regression, security, usability, performance, acceptance 
     * @type {string}
     * @memberof GetCasesFiltersParameter
     */
    'type'?: string;
    /**
     * A list of behavior values separated by comma. Possible values: undefined, positive negative, destructive 
     * @type {string}
     * @memberof GetCasesFiltersParameter
     */
    'behavior'?: string;
    /**
     * A list of values separated by comma. Possible values: is-not-automated, automated to-be-automated 
     * @type {string}
     * @memberof GetCasesFiltersParameter
     */
    'automation'?: string;
    /**
     * A list of values separated by comma. Possible values: actual, draft deprecated 
     * @type {string}
     * @memberof GetCasesFiltersParameter
     */
    'status'?: string;
}

