/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
    /**
     * Test suite title.
     * @type {string}
     * @memberof InlineObject1
     */
    'title'?: string;
    /**
     * Test suite description.
     * @type {string}
     * @memberof InlineObject1
     */
    'description'?: string;
    /**
     * Test suite preconditions
     * @type {string}
     * @memberof InlineObject1
     */
    'preconditions'?: string;
    /**
     * Parent suite ID
     * @type {number}
     * @memberof InlineObject1
     */
    'parent_id'?: number | null;
}

