/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Milestone
 */
export interface Milestone {
    /**
     * 
     * @type {number}
     * @memberof Milestone
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'status'?: MilestoneStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'due_date'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Milestone
     */
    'updated'?: string | null;
}

/**
    * @export
    * @enum {string}
    */
export enum MilestoneStatusEnum {
    COMPLETED = 'completed',
    ACTIVE = 'active'
}


