/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Plan
 */
export interface Plan {
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof Plan
     */
    'cases_count'?: number;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'created'?: string;
    /**
     * 
     * @type {string}
     * @memberof Plan
     */
    'updated'?: string | null;
}

