/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { PlanDetailedAllOfCases } from './plan-detailed-all-of-cases';

/**
 * 
 * @export
 * @interface PlanDetailedAllOf
 */
export interface PlanDetailedAllOf {
    /**
     * 
     * @type {number}
     * @memberof PlanDetailedAllOf
     */
    'average_time'?: number;
    /**
     * 
     * @type {Array<PlanDetailedAllOfCases>}
     * @memberof PlanDetailedAllOf
     */
    'cases'?: Array<PlanDetailedAllOfCases>;
}

