/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RunMilestone
 */
export interface RunMilestone {
    /**
     * 
     * @type {string}
     * @memberof RunMilestone
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof RunMilestone
     */
    'description'?: string;
}

