/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RunStats
 */
export interface RunStats {
    /**
     * 
     * @type {number}
     * @memberof RunStats
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof RunStats
     */
    'untested'?: number;
    /**
     * 
     * @type {number}
     * @memberof RunStats
     */
    'passed'?: number;
    /**
     * 
     * @type {number}
     * @memberof RunStats
     */
    'failed'?: number;
    /**
     * 
     * @type {number}
     * @memberof RunStats
     */
    'blocked'?: number;
    /**
     * 
     * @type {number}
     * @memberof RunStats
     */
    'skipped'?: number;
    /**
     * 
     * @type {number}
     * @memberof RunStats
     */
    'retest'?: number;
    /**
     * 
     * @type {number}
     * @memberof RunStats
     */
    'in_progress'?: number;
    /**
     * 
     * @type {number}
     * @memberof RunStats
     */
    'invalid'?: number;
}

