/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SharedStepCreateSteps } from './shared-step-create-steps';

/**
 * 
 * @export
 * @interface SharedStepUpdate
 */
export interface SharedStepUpdate {
    /**
     * 
     * @type {string}
     * @memberof SharedStepUpdate
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedStepUpdate
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedStepUpdate
     */
    'expected_result'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedStepUpdate
     */
    'data'?: string;
    /**
     * 
     * @type {Array<SharedStepCreateSteps>}
     * @memberof SharedStepUpdate
     */
    'steps'?: Array<SharedStepCreateSteps>;
}

