/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AttachmentHash } from './attachment-hash';

/**
 * 
 * @export
 * @interface SharedStepStepsInner
 */
export interface SharedStepStepsInner {
    /**
     * 
     * @type {string}
     * @memberof SharedStepStepsInner
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedStepStepsInner
     */
    'hash'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedStepStepsInner
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedStepStepsInner
     */
    'expected_result'?: string;
    /**
     * 
     * @type {Array<AttachmentHash>}
     * @memberof SharedStepStepsInner
     */
    'attachments'?: Array<AttachmentHash>;
}

