/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SharedStepContentCreate
 */
export interface SharedStepContentCreate {
    /**
     * 
     * @type {string}
     * @memberof SharedStepContentCreate
     */
    'action': string;
    /**
     * 
     * @type {string}
     * @memberof SharedStepContentCreate
     */
    'hash'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedStepContentCreate
     */
    'expected_result'?: string;
    /**
     * 
     * @type {string}
     * @memberof SharedStepContentCreate
     */
    'data'?: string;
    /**
     * A list of Attachment hashes.
     * @type {Array<string>}
     * @memberof SharedStepContentCreate
     */
    'attachments'?: Array<string>;
}

