/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TestCaseUpdateSteps
 */
export interface TestCaseUpdateSteps {
    /**
     * 
     * @type {string}
     * @memberof TestCaseUpdateSteps
     */
    'action'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCaseUpdateSteps
     */
    'expected_result'?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCaseUpdateSteps
     */
    'data'?: string;
    /**
     * 
     * @type {number}
     * @memberof TestCaseUpdateSteps
     */
    'position'?: number;
}

