/* tslint:disable */
/* eslint-disable */
/**
 * Qase.io API
 * Qase API Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Response } from './response';
import { User } from './user';
import { UserResponseAllOf } from './user-response-all-of';

/**
 * @type UserResponse
 * @export
 */
export type UserResponse = Response & UserResponseAllOf;


